import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { database } from "@/platform/persistence/prisma";
import { addInventory, adjustInventory, archiveProduct, assignBarcode, createProduct, generateBarcode, listCategories, readProduct, searchProducts } from "./inventory-service";

const databaseTests = process.env.TEST_DATABASE_URL || process.env.TEST_DATABASE ? describe : describe.skip;

databaseTests("inventory PostgreSQL integration", () => {
  const suffix = `${Date.now()}-${Math.random().toString(36).slice(2)}`;
  let ownerId="", staffId="", outsiderId="", storeId="", otherStoreId="", productId="";
  beforeAll(async () => {
    const db=database();
    const [owner,staff,outsider]=await Promise.all([
      db.user.create({data:{email:`phase2-owner-${suffix}@example.test`}}),db.user.create({data:{email:`phase2-staff-${suffix}@example.test`}}),db.user.create({data:{email:`phase2-other-${suffix}@example.test`}})
    ]);ownerId=owner.id;staffId=staff.id;outsiderId=outsider.id;
    const store=await db.store.create({data:{name:`Phase 2 ${suffix}`,preference:{create:{}},memberships:{create:[{userId:ownerId,role:"OWNER"},{userId:staffId,role:"STAFF"}]}}});storeId=store.id;
    const other=await db.store.create({data:{name:`Other ${suffix}`,preference:{create:{}},memberships:{create:{userId:outsiderId,role:"OWNER"}}}});otherStoreId=other.id;
  });
  afterAll(async()=>{const db=database();for(const id of [storeId,otherStoreId]){if(!id)continue;await db.auditEvent.deleteMany({where:{storeId:id}});await db.idempotencyKey.deleteMany({where:{storeId:id}});await db.barcodeLabel.deleteMany({where:{storeId:id}});await db.productBarcode.deleteMany({where:{storeId:id}});await db.inventoryMovement.deleteMany({where:{storeId:id}});await db.inventoryBalance.deleteMany({where:{storeId:id}});await db.productSupplierReference.deleteMany({where:{storeId:id}});await db.product.deleteMany({where:{storeId:id}});await db.category.deleteMany({where:{storeId:id}});await db.supplier.deleteMany({where:{storeId:id}});await db.storeMembership.deleteMany({where:{storeId:id}});await db.storePreference.deleteMany({where:{storeId:id}});await db.store.deleteMany({where:{id}})}await db.user.deleteMany({where:{id:{in:[ownerId,staffId,outsiderId]}}})});

  it("creates product, balance, opening movement and related catalog records atomically",async()=>{const input={name:"Fresh Eggs",category:"Dairy",supplier:"Local Farm",sellingUnit:"PIECE",sellingPrice:8,latestPurchaseCost:6,lowStockThreshold:5,startingQuantity:12,barcodeChoice:"NONE",idempotencyKey:`create-${suffix}`} as const;const result=await createProduct(ownerId,input);productId=result.id;expect((await createProduct(ownerId,input)).id).toBe(productId);const detail=await readProduct(ownerId,productId);expect(detail.quantity).toBe(12);expect(detail.movements).toHaveLength(1);expect(detail.movements[0]).toMatchObject({previousQuantity:0,quantityDelta:12,resultingQuantity:12});});
  it("applies an add-stock request at most once",async()=>{const input={quantity:5,purchaseCost:6.5,idempotencyKey:`add-${suffix}`};const first=await addInventory(ownerId,productId,input);const second=await addInventory(ownerId,productId,input);expect(second).toEqual(first);expect((await readProduct(ownerId,productId)).quantity).toBe(17);});
  it("rejects negative results without changing balance or history",async()=>{const before=await readProduct(ownerId,productId);await expect(adjustInventory(ownerId,productId,{delta:-999,reason:"DAMAGED",idempotencyKey:`negative-${suffix}`})).rejects.toThrow("NEGATIVE_STOCK");const after=await readProduct(ownerId,productId);expect(after.quantity).toBe(before.quantity);expect(after.movements).toHaveLength(before.movements.length);});
  it("preserves barcode uniqueness and replacement history",async()=>{await assignBarcode(ownerId,productId,{value:"4800016640017",idempotencyKey:`assign-${suffix}`});const generated=await generateBarcode(ownerId,productId,{idempotencyKey:`generate-${suffix}`});const replacement=await generateBarcode(ownerId,productId,{idempotencyKey:`replace-${suffix}`},true);expect(replacement.replacesId).toBe(generated.id);const detail=await readProduct(ownerId,productId);expect(detail.barcodes.find(code=>code.id===generated.id)?.status).toBe("RETIRED");expect(detail.barcodes.find(code=>code.id===replacement.id)?.status).toBe("ACTIVE");});
  it("enforces role and store boundaries",async()=>{await expect(addInventory(staffId,productId,{quantity:1,idempotencyKey:`staff-${suffix}`})).rejects.toThrow("Only the store owner");await expect(readProduct(outsiderId,productId)).rejects.toThrow("Product not found");});
  it("suggests matching categories only from the active store",async()=>{expect((await listCategories(ownerId,"dai")).items).toEqual([expect.objectContaining({name:"Dairy",productCount:1})]);expect((await listCategories(outsiderId,"dai")).items).toEqual([]);});
  it("serializes concurrent changes and reconciles balance to movements",async()=>{await Promise.all([adjustInventory(ownerId,productId,{delta:-1,reason:"CORRECTION",idempotencyKey:`concurrent-a-${suffix}`}),adjustInventory(ownerId,productId,{delta:-1,reason:"CORRECTION",idempotencyKey:`concurrent-b-${suffix}`})]);const detail=await readProduct(ownerId,productId);expect(detail.quantity).toBe(detail.movements.reduce((sum,movement)=>sum+movement.quantityDelta,0));});
  it("archives without deleting history or active search visibility",async()=>{await archiveProduct(ownerId,productId);const detail=await readProduct(ownerId,productId);expect(detail.status).toBe("ARCHIVED");expect(detail.movements.length).toBeGreaterThan(0);expect((await searchProducts(ownerId,{query:"Fresh Eggs"})).items).toHaveLength(0);await expect(addInventory(ownerId,productId,{quantity:1,idempotencyKey:`archived-${suffix}`})).rejects.toThrow("Archived products");});
});
