"use client";
import { useState, type FormEvent } from "react";
import { AppToast } from "@/components/app-toast";
import { Icon } from "@/components/icon";
import { LoadingButtonContent } from "@/components/loading";
import { PasswordInput } from "@/components/password-input";

type SettingsData = {
  role: "OWNER" | "STAFF";
  user: { name: string | null; email: string; phone: string | null; preferredLanguage: "EN" | "FIL"; preferredTheme: "SYSTEM" | "LIGHT" | "DARK" };
  store: { name: string; storeType: string; address: string | null; contact: string | null };
  preference: { lowStockEnabled: boolean; dailySummaryEnabled: boolean; receiptNotifications: boolean; receiptRetentionDays: number };
  subscription: { plan: "PILOT" | "TRIAL" | "STANDARD"; status: "TRIALING" | "ACTIVE" | "GRACE" | "RESTRICTED" | "CANCELED"; trialEndsAt: string | null; currentPeriodEndsAt: string | null; graceEndsAt: string | null };
  members: { id: string; role: "OWNER" | "STAFF"; status: string; user: { name: string | null; email: string } }[];
  invitations: { id: string; email: string; expiresAt: string; createdAt: string }[];
};

const copy = {
  EN: { title: "Settings", intro: "A few preferences — nothing technical to configure.", store: "Store information", storeName: "Store name", address: "Address", contact: "Contact number", storeType: "Store type", account: "Account", yourName: "Your name", email: "Email address", mobile: "Mobile number", password: "Password", changePassword: "Change password", currentPassword: "Current password", newPassword: "New password", updatePassword: "Update password", preferences: "Preferences", language: "Language", theme: "Appearance", system: "Use device setting", light: "Light", dark: "Dark", notifications: "Notifications", low: "Low stock alerts", lowHelp: "Get a reminder before you run out", daily: "Daily summary", dailyHelp: "A short recap every evening", receipt: "New receipt ready", receiptHelp: "When a scanned receipt is ready to review", retention: "Receipt photo retention", retentionHelp: "Structured receipt and inventory history is always kept.", oneYear: "1 year", threeYears: "3 years", sevenYears: "7 years", team: "Staff access", teamHelp: "Invite staff without sharing your owner password.", inviteEmail: "Staff email address", invite: "Create invitation", copyLink: "Copy link", revoke: "Revoke", active: "Active", pending: "Pending", plan: "Plan", pilot: "Pilot access", trial: "Free trial", standard: "Standard", trialing: "Trial active", activePlan: "Active", grace: "Payment attention needed", restricted: "Read-only", canceled: "Canceled", planHelp: "Your records and exports remain available even if changes are paused.", save: "Save changes", saved: "Settings saved.", passwordSaved: "Password updated.", inviteCreated: "Invitation created. Copy and send the private link.", copied: "Invitation link copied.", genericError: "We couldn't save that. Nothing was changed.", ownerOnly: "Only the store owner can change store, staff, plan, and retention settings." },
  FIL: { title: "Mga Setting", intro: "Ilang kagustuhan lang — walang teknikal na dapat i-configure.", store: "Impormasyon ng tindahan", storeName: "Pangalan ng tindahan", address: "Address", contact: "Numero ng contact", storeType: "Uri ng tindahan", account: "Account", yourName: "Iyong pangalan", email: "Email address", mobile: "Numero ng cellphone", password: "Password", changePassword: "Palitan ang password", currentPassword: "Kasalukuyang password", newPassword: "Bagong password", updatePassword: "I-update ang password", preferences: "Kagustuhan", language: "Wika", theme: "Itsura", system: "Sundin ang device", light: "Maliwanag", dark: "Madilim", notifications: "Mga Abiso", low: "Abiso sa paubos na stock", lowHelp: "Bigyan ng paalala bago maubos", daily: "Pang-araw-araw na buod", dailyHelp: "Maikling buod tuwing gabi", receipt: "Bagong resibong handa", receiptHelp: "Kapag handa nang suriin ang na-scan na resibo", retention: "Pag-iingat ng larawan ng resibo", retentionHelp: "Palaging nakaingat ang detalye ng resibo at kasaysayan ng imbentaryo.", oneYear: "1 taon", threeYears: "3 taon", sevenYears: "7 taon", team: "Access ng staff", teamHelp: "Mag-imbita ng staff nang hindi ibinabahagi ang owner password.", inviteEmail: "Email ng staff", invite: "Gumawa ng imbitasyon", copyLink: "Kopyahin ang link", revoke: "Bawiin", active: "Aktibo", pending: "Naghihintay", plan: "Plan", pilot: "Pilot access", trial: "Libreng trial", standard: "Standard", trialing: "Aktibo ang trial", activePlan: "Aktibo", grace: "Kailangang ayusin ang bayad", restricted: "Basahin lamang", canceled: "Kinansela", planHelp: "Mananatiling available ang records at exports kahit pansamantalang ihinto ang pagbabago.", save: "I-save ang pagbabago", saved: "Nai-save ang mga setting.", passwordSaved: "Na-update ang password.", inviteCreated: "Nagawa ang imbitasyon. Kopyahin at ipadala ang pribadong link.", copied: "Nakopya ang invitation link.", genericError: "Hindi ito na-save. Walang nabago.", ownerOnly: "May-ari lamang ang maaaring magbago ng tindahan, staff, plan, at retention." },
} as const;

async function responseMessage(response: Response, fallback: string) { const body = await response.json().catch(() => ({})) as { error?: string }; if (!response.ok) throw new Error(body.error || fallback); return body; }

export function SettingsClient({ initial, locale }: { initial: SettingsData; locale: "EN" | "FIL" }) {
  const t = copy[locale]; const owner = initial.role === "OWNER";
  const [data, setData] = useState(initial); const [pending, setPending] = useState(false); const [toast, setToast] = useState(""); const [error, setError] = useState(""); const [passwordOpen, setPasswordOpen] = useState(false); const [inviteUrl, setInviteUrl] = useState("");
  const field = (key: keyof SettingsData["store"], value: string) => setData(current => ({ ...current, store: { ...current.store, [key]: value } }));
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); try { const response = await fetch("/api/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: data.user.name, phone: data.user.phone, storeName: data.store.name, storeType: data.store.storeType, address: data.store.address, contact: data.store.contact, language: data.user.preferredLanguage, theme: data.user.preferredTheme, ...data.preference }) }); await responseMessage(response, t.genericError); document.cookie = `tindahan-language=${data.user.preferredLanguage};path=/;max-age=31536000;samesite=lax`; document.cookie = `tindahan-theme=${data.user.preferredTheme};path=/;max-age=31536000;samesite=lax`; document.documentElement.lang = data.user.preferredLanguage === "FIL" ? "fil" : "en"; setToast(t.saved); } catch (cause) { setError(cause instanceof Error ? cause.message : t.genericError); } finally { setPending(false); } }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setPending(true); setError(""); try { const response = await fetch("/api/settings/password", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword: form.get("currentPassword"), newPassword: form.get("newPassword") }) }); await responseMessage(response, t.genericError); formElement.reset(); setPasswordOpen(false); setToast(t.passwordSaved); } catch (cause) { setError(cause instanceof Error ? cause.message : t.genericError); } finally { setPending(false); } }
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setPending(true); setError(""); try { const response = await fetch("/api/settings/staff", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: form.get("email") }) }); const result = await responseMessage(response, t.genericError) as { id: string; email: string; expiresAt: string; inviteUrl: string }; setData(current => ({ ...current, invitations: [{ id: result.id, email: result.email, expiresAt: result.expiresAt, createdAt: new Date().toISOString() }, ...current.invitations] })); setInviteUrl(result.inviteUrl); formElement.reset(); setToast(t.inviteCreated); } catch (cause) { setError(cause instanceof Error ? cause.message : t.genericError); } finally { setPending(false); } }
  async function revoke(id: string) { setPending(true); setError(""); try { const response = await fetch(`/api/settings/staff/invitations/${id}`, { method: "DELETE" }); await responseMessage(response, t.genericError); setData(current => ({ ...current, invitations: current.invitations.filter(item => item.id !== id) })); setInviteUrl(""); } catch (cause) { setError(cause instanceof Error ? cause.message : t.genericError); } finally { setPending(false); } }
  const planLabel = data.subscription.plan === "PILOT" ? t.pilot : data.subscription.plan === "TRIAL" ? t.trial : t.standard;
  const statusLabel = ({ TRIALING: t.trialing, ACTIVE: t.activePlan, GRACE: t.grace, RESTRICTED: t.restricted, CANCELED: t.canceled })[data.subscription.status];
  return <><div className="content-header settings-header"><h1>{t.title}</h1><p className="text-muted">{t.intro}</p></div>{error && <p className="form-alert settings-alert" role="alert">{error}</p>}{!owner && <div className="info-banner settings-alert"><Icon name="info"/><span>{t.ownerOnly}</span></div>}
    <form onSubmit={save} className="settings-form">
      {owner && <SettingsGroup title={t.store}><div className="settings-fields"><Field label={t.storeName}><input className="input" value={data.store.name} onChange={e => field("name", e.target.value)} required/></Field><div className="form-row"><Field label={t.address}><input className="input" value={data.store.address ?? ""} onChange={e => field("address", e.target.value)}/></Field><Field label={t.contact}><input className="input" value={data.store.contact ?? ""} onChange={e => field("contact", e.target.value)}/></Field></div><Field label={t.storeType}><select className="select" value={data.store.storeType} onChange={e => field("storeType", e.target.value)}><option>Sari-sari store</option><option>Mini-mart</option><option>Convenience store</option><option>Other small store</option></select></Field></div></SettingsGroup>}
      <SettingsGroup title={t.account}><div className="settings-fields"><div className="form-row"><Field label={t.yourName}><input className="input" value={data.user.name ?? ""} onChange={e => setData(c => ({ ...c, user: { ...c.user, name: e.target.value } }))} required/></Field><Field label={t.mobile}><input className="input" type="tel" value={data.user.phone ?? ""} onChange={e => setData(c => ({ ...c, user: { ...c.user, phone: e.target.value } }))}/></Field></div><Field label={t.email}><input className="input" value={data.user.email} disabled/></Field><div className="settings-password-row"><span><strong>{t.password}</strong></span><button className="btn btn-secondary" type="button" onClick={() => setPasswordOpen(value => !value)}>{t.changePassword}</button></div></div></SettingsGroup>
      <SettingsGroup title={t.preferences}><div className="settings-row"><span className="row-main"><span className="row-title">{t.language}</span></span><div className="segmented"><button type="button" className={data.user.preferredLanguage === "EN" ? "active" : ""} onClick={() => setData(c => ({ ...c, user: { ...c.user, preferredLanguage: "EN" } }))}>EN</button><button type="button" className={data.user.preferredLanguage === "FIL" ? "active" : ""} onClick={() => setData(c => ({ ...c, user: { ...c.user, preferredLanguage: "FIL" } }))}>FIL</button></div></div><div className="settings-row"><span className="row-main"><span className="row-title">{t.theme}</span></span><select className="select settings-select" value={data.user.preferredTheme} onChange={e => setData(c => ({ ...c, user: { ...c.user, preferredTheme: e.target.value as SettingsData["user"]["preferredTheme"] } }))}><option value="SYSTEM">{t.system}</option><option value="LIGHT">{t.light}</option><option value="DARK">{t.dark}</option></select></div></SettingsGroup>
      {owner && <SettingsGroup title={t.notifications}><Toggle label={t.low} help={t.lowHelp} checked={data.preference.lowStockEnabled} onChange={value => setData(c => ({ ...c, preference: { ...c.preference, lowStockEnabled: value } }))}/><Toggle label={t.daily} help={t.dailyHelp} checked={data.preference.dailySummaryEnabled} onChange={value => setData(c => ({ ...c, preference: { ...c.preference, dailySummaryEnabled: value } }))}/><Toggle label={t.receipt} help={t.receiptHelp} checked={data.preference.receiptNotifications} onChange={value => setData(c => ({ ...c, preference: { ...c.preference, receiptNotifications: value } }))}/></SettingsGroup>}
      {owner && <SettingsGroup title={t.retention}><div className="settings-row"><span className="row-main"><span className="row-title">{t.retention}</span><span className="row-meta">{t.retentionHelp}</span></span><select className="select settings-select" value={data.preference.receiptRetentionDays} onChange={e => setData(c => ({ ...c, preference: { ...c.preference, receiptRetentionDays: Number(e.target.value) } }))}><option value="365">{t.oneYear}</option><option value="1095">{t.threeYears}</option><option value="2555">{t.sevenYears}</option></select></div></SettingsGroup>}
      <button className="btn btn-primary settings-save" disabled={pending} type="submit">{pending ? <LoadingButtonContent message={t.save}/> : t.save}</button>
    </form>
    {passwordOpen && <SettingsGroup title={t.changePassword}><form className="settings-fields" onSubmit={changePassword}><div className="form-row"><div className="field"><label className="field-label" htmlFor="current-password">{t.currentPassword}</label><PasswordInput id="current-password" name="currentPassword" autoComplete="current-password" required locale={locale}/></div><div className="field"><label className="field-label" htmlFor="new-password">{t.newPassword}</label><PasswordInput id="new-password" name="newPassword" autoComplete="new-password" minLength={10} required locale={locale}/></div></div><button className="btn btn-secondary settings-inline-action" disabled={pending}>{t.updatePassword}</button></form></SettingsGroup>}
    {owner && <><SettingsGroup title={t.team}><p className="text-muted text-sm settings-group-help">{t.teamHelp}</p><form className="settings-invite-form" onSubmit={invite}><input className="input" name="email" type="email" placeholder="staff@example.com" aria-label={t.inviteEmail} required/><button className="btn btn-secondary" disabled={pending}><Icon name="plus"/>{t.invite}</button></form>{inviteUrl && <div className="info-banner invite-link"><span className="text-sm">{inviteUrl}</span><button className="btn btn-secondary btn-sm" type="button" onClick={async () => { await navigator.clipboard.writeText(inviteUrl); setToast(t.copied); }}>{t.copyLink}</button></div>}<div className="settings-team-list">{data.members.map(member => <div className="row-item" key={member.id}><span className="avatar">{(member.user.name || member.user.email).slice(0, 2).toUpperCase()}</span><span className="row-main"><span className="row-title">{member.user.name || member.user.email}</span><span className="row-meta">{member.user.email} · {member.role === "OWNER" ? "Owner" : "Staff"}</span></span><span className="badge badge-success">{t.active}</span></div>)}{data.invitations.map(invitation => <div className="row-item" key={invitation.id}><span className="avatar"><Icon name="plus"/></span><span className="row-main"><span className="row-title">{invitation.email}</span><span className="row-meta">{t.pending}</span></span><button className="btn btn-ghost btn-sm" type="button" disabled={pending} onClick={() => revoke(invitation.id)}>{t.revoke}</button></div>)}</div></SettingsGroup><SettingsGroup title={t.plan}><div className="settings-plan-row"><span><strong>{planLabel}</strong><span className="row-meta">{t.planHelp}</span></span><span className={`badge ${data.subscription.status === "RESTRICTED" || data.subscription.status === "CANCELED" ? "badge-danger" : data.subscription.status === "GRACE" ? "badge-warning" : "badge-success"}`}>{statusLabel}</span></div></SettingsGroup></>}
    <AppToast message={toast} locale={locale} onDismiss={() => setToast("")}/></>;
}

function SettingsGroup({ title, children }: { title: string; children: React.ReactNode }) { return <section className="settings-group"><h2 className="settings-group-title">{title}</h2><div className="card settings-card">{children}</div></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span className="field-label">{label}</span>{children}</label>; }
function Toggle({ label, help, checked, onChange }: { label: string; help: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="settings-row"><span className="row-main"><span className="row-title">{label}</span><span className="row-meta">{help}</span></span><label className="switch"><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} aria-label={label}/><span className="switch-track"/><span className="switch-thumb"/></label></div>; }
