import { createHash, randomUUID } from "node:crypto";
import { z } from "zod";
import { database } from "@/platform/persistence/prisma";
import { resolveStoreContext } from "@/modules/stores/application/store-context";
import { normalizeName, productUnits, unitDetails } from "@/modules/catalog/domain/product";
import { validateBarcode } from "@/modules/barcodes/domain/barcode";
import { confirmSaleInput, mergeSaleLines } from "../domain/sale";
import { SalesError, type StockConflict } from "./errors";
import { mayRecordSale, requireSaleOwner } from "./policy";

const searchQuery = z.string().trim().max(160);
const historyQuery = z.object({ range: z.enum(["today", "week", "month"]).default("today"), cursor: z.string().optional(), limit: z.coerce.number().int().min(1).max(50).default(20) });
const correctionInput = z.object({ reason: z.string().trim().min(3).max(240), idempotencyKey: z.string().min(8).max(120) });
const productCreateInput = z.object({ name: z.string().trim().min(1).max(160), sellingPrice: z.coerce.number().min(0), startingQuantity: z.coerce.number().int().min(0), sellingUnit: z.enum(productUnits), otherUnitRaw: z.string().trim().max(40).optional().nullable(), barcode: z.string(), idempotencyKey: z.string().min(8).max(120) });

function hash(value: unknown) { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
async function contextFor(userId: string) { const context = await resolveStoreContext(userId); if (!context) throw new SalesError("FORBIDDEN", "You do not have access to a store.", 403); return context; }
function productDto(product: { id:string; name:string; sellingUnit:string; otherUnitRaw:string|null; sellingPrice:{toString():string}; lowStockThreshold:number; balance:{quantity:number}|null }) { return { id:product.id, name:product.name, sellingUnit:product.sellingUnit, otherUnitRaw:product.otherUnitRaw, sellingPrice:product.sellingPrice.toString(), quantity:product.balance?.quantity ?? 0, lowStockThreshold:product.lowStockThreshold }; }

export async function searchSaleProducts(userId: string, rawQuery = "", limit = 8) {
  const { store } = await contextFor(userId); const query = searchQuery.parse(rawQuery); const normalizedBarcode = query.replace(/[\s-]/g, "");
  const products = await database().product.findMany({ where: { storeId:store.id, status:"ACTIVE", ...(query ? { OR:[{name:{contains:query,mode:"insensitive"}},{normalizedName:{contains:normalizeName(query)}},{barcodes:{some:{status:"ACTIVE",normalizedValue:{contains:normalizedBarcode}}}}] } : {}) }, include:{balance:true}, orderBy:[{normalizedName:"asc"},{id:"asc"}], take:Math.min(Math.max(limit,1),20) });
  return { items:products.map(productDto) };
}

export async function saleSuggestions(userId: string) {
  const { store } = await contextFor(userId);
  const recentLines = await database().saleLine.findMany({ where:{storeId:store.id,sale:{status:"CONFIRMED"},product:{status:"ACTIVE"}}, distinct:["productId"], orderBy:{sale:{confirmedAt:"desc"}}, take:6, include:{product:{include:{balance:true}}} });
  const frequent = await database().saleLine.groupBy({ by:["productId"], where:{storeId:store.id,sale:{status:"CONFIRMED"},product:{status:"ACTIVE"}}, _sum:{quantity:true}, orderBy:{_sum:{quantity:"desc"}}, take:8 });
  const frequentProducts = frequent.length ? await database().product.findMany({where:{storeId:store.id,status:"ACTIVE",id:{in:frequent.map(item=>item.productId)}},include:{balance:true}}) : [];
  const byId=new Map(frequentProducts.map(product=>[product.id,product]));
  return { recent:recentLines.map(line=>productDto(line.product)), frequent:frequent.map(item=>byId.get(item.productId)).filter((product):product is NonNullable<typeof product>=>Boolean(product)).map(productDto) };
}

export async function resolveSaleBarcode(userId: string, rawCode: string) {
  const { store } = await contextFor(userId); let code:string; try { code=validateBarcode(rawCode); } catch { throw new SalesError("INVALID_BARCODE", "Enter a valid 8–14 digit barcode.", 400); }
  const barcode=await database().productBarcode.findFirst({where:{storeId:store.id,normalizedValue:code,status:"ACTIVE",product:{status:"ACTIVE"}},include:{product:{include:{balance:true}}}});
  return barcode ? { found:true as const, product:productDto(barcode.product) } : { found:false as const, code };
}

export async function createScannedProduct(userId:string, raw:unknown) {
  const {store,role}=await contextFor(userId); requireSaleOwner(role); const input=productCreateInput.parse(raw); const barcode=validateBarcode(input.barcode); const requestHash=hash(input); const units=unitDetails(input.sellingUnit,input.otherUnitRaw); const correlationId=randomUUID();
  try{return await database().$transaction(async tx=>{const prior=await tx.idempotencyKey.findUnique({where:{storeId_scope_key:{storeId:store.id,scope:"CREATE_SCANNED_PRODUCT",key:input.idempotencyKey}}});if(prior){if(prior.requestHash!==requestHash)throw new SalesError("IDEMPOTENCY_CONFLICT","This request was already used for different product details.",409);return prior.response;}
    const product=await tx.product.create({data:{storeId:store.id,name:input.name,normalizedName:normalizeName(input.name),sellingUnit:input.sellingUnit,...units,sellingPrice:input.sellingPrice,lowStockThreshold:0,balance:{create:{storeId:store.id,quantity:input.startingQuantity}},barcodes:{create:{storeId:store.id,assignedById:userId,value:barcode,normalizedValue:barcode,type:"MANUFACTURER"}}}});
    if(input.startingQuantity>0)await tx.inventoryMovement.create({data:{storeId:store.id,productId:product.id,actorId:userId,type:"OPENING",quantityDelta:input.startingQuantity,previousQuantity:0,resultingQuantity:input.startingQuantity,sourceType:"PRODUCT_CREATION",sourceId:product.id,correlationId}});
    const response={id:product.id};await tx.auditEvent.create({data:{storeId:store.id,actorId:userId,action:"PRODUCT_CREATED_FROM_SALE",entityType:"Product",entityId:product.id,correlationId,after:{name:input.name,barcode}}});await tx.idempotencyKey.create({data:{storeId:store.id,scope:"CREATE_SCANNED_PRODUCT",key:input.idempotencyKey,requestHash,status:"COMPLETED",response,expiresAt:new Date(Date.now()+86_400_000)}});return response;},{isolationLevel:"Serializable"});}catch(error){if((error as {code?:string}).code==="P2002")throw new SalesError("DUPLICATE_BARCODE","That barcode is already linked to another product.",409);throw error;}
}

export async function confirmSale(userId:string, raw:unknown) {
  const {store,role}=await contextFor(userId);mayRecordSale(role);const parsed=confirmSaleInput.parse(raw);const lines=mergeSaleLines(parsed.lines);const requestHash=hash(lines);
  for(let attempt=0;attempt<3;attempt++)try{return await database().$transaction(async tx=>{const prior=await tx.idempotencyKey.findUnique({where:{storeId_scope_key:{storeId:store.id,scope:"CONFIRM_SALE",key:parsed.idempotencyKey}}});if(prior){if(prior.requestHash!==requestHash)throw new SalesError("IDEMPOTENCY_CONFLICT","This confirmation key was already used for a different sale.",409);return prior.response as {saleId:string;totalAmount:string;totalQuantity:number;confirmedAt:string};}
    const products=await tx.product.findMany({where:{storeId:store.id,status:"ACTIVE",id:{in:lines.map(line=>line.productId)}},include:{balance:true}});const byId=new Map(products.map(product=>[product.id,product]));if(products.length!==lines.length)throw new SalesError("PRODUCT_UNAVAILABLE","One or more products are no longer available. Remove them and try again.",409);
    const conflicts:StockConflict[]=lines.flatMap(line=>{const product=byId.get(line.productId)!;const available=product.balance?.quantity??0;return line.quantity>available?[{productId:product.id,name:product.name,requested:line.quantity,available}]:[]});if(conflicts.length)throw new SalesError("INSUFFICIENT_STOCK","Stock changed while you were reviewing this sale. Update the named products and try again.",409,conflicts);
    const correlationId=randomUUID();let totalAmount=0,totalQuantity=0;for(const line of lines){const product=byId.get(line.productId)!;const previous=product.balance!.quantity;const update=await tx.inventoryBalance.updateMany({where:{storeId:store.id,productId:product.id,version:product.balance!.version,quantity:{gte:line.quantity}},data:{quantity:{decrement:line.quantity},version:{increment:1}}});if(update.count!==1)throw new SalesError("STOCK_CHANGED","Stock changed while you were reviewing this sale. Refresh quantities and try again.",409,[{productId:product.id,name:product.name,requested:line.quantity,available:previous}]);totalAmount+=Number(product.sellingPrice)*line.quantity;totalQuantity+=line.quantity;}
    const sale=await tx.sale.create({data:{storeId:store.id,createdById:userId,status:"CONFIRMED",totalAmount,totalQuantity,idempotencyKey:parsed.idempotencyKey,correlationId,confirmedAt:new Date(),lines:{create:lines.map(line=>{const product=byId.get(line.productId)!;return{storeId:store.id,productId:product.id,productNameSnapshot:product.name,unitSnapshot:product.sellingUnit,otherUnitSnapshot:product.otherUnitRaw,quantity:line.quantity,unitPrice:product.sellingPrice,lineTotal:Number(product.sellingPrice)*line.quantity};})}}});
    for(const line of lines){const product=byId.get(line.productId)!;await tx.inventoryMovement.create({data:{storeId:store.id,productId:product.id,actorId:userId,type:"SALE",quantityDelta:-line.quantity,previousQuantity:product.balance!.quantity,resultingQuantity:product.balance!.quantity-line.quantity,sourceType:"SALE",sourceId:sale.id,correlationId}});}
    const response={saleId:sale.id,totalAmount:sale.totalAmount.toString(),totalQuantity:sale.totalQuantity,confirmedAt:sale.confirmedAt!.toISOString()};await tx.auditEvent.create({data:{storeId:store.id,actorId:userId,action:"SALE_CONFIRMED",entityType:"Sale",entityId:sale.id,correlationId,after:{totalQuantity,totalAmount}}});await tx.idempotencyKey.create({data:{storeId:store.id,scope:"CONFIRM_SALE",key:parsed.idempotencyKey,requestHash,status:"COMPLETED",response,expiresAt:new Date(Date.now()+7*86_400_000)}});return response;},{isolationLevel:"Serializable"});}catch(error){if((error as {code?:string}).code==="P2034"&&attempt<2)continue;throw error;}throw new SalesError("STOCK_CHANGED","Stock changed. Review the draft and try again.",409);
}

function rangeStart(range:"today"|"week"|"month"){const now=new Date();const start=new Date(now);if(range==="today")start.setHours(0,0,0,0);else if(range==="week")start.setDate(now.getDate()-7);else start.setMonth(now.getMonth()-1);return start;}
export async function listSales(userId:string, raw:unknown={}) { const {store}=await contextFor(userId);const input=historyQuery.parse(raw);const start=rangeStart(input.range);const records=await database().sale.findMany({where:{storeId:store.id,status:{in:["CONFIRMED","CORRECTED"]},confirmedAt:{gte:start}},take:input.limit+1,...(input.cursor?{cursor:{id:input.cursor},skip:1}:{}),orderBy:[{confirmedAt:"desc"},{id:"desc"}],include:{createdBy:{select:{name:true,email:true}},lines:{select:{productNameSnapshot:true,quantity:true}}}});const items=records.slice(0,input.limit).map(sale=>({...sale,status:sale.status as "CONFIRMED"|"CORRECTED",createdAt:sale.createdAt.toISOString(),confirmedAt:sale.confirmedAt?.toISOString()??null,totalAmount:sale.totalAmount.toString()}));const summary=await database().sale.aggregate({where:{storeId:store.id,status:"CONFIRMED",confirmedAt:{gte:start}},_sum:{totalAmount:true,totalQuantity:true},_count:{id:true}});return{items,nextCursor:records.length>input.limit?records[input.limit-1]?.id??null:null,summary:{amount:summary._sum.totalAmount?.toString()??"0",quantity:summary._sum.totalQuantity??0,count:summary._count.id}}; }

export async function readSale(userId:string,saleId:string){const {store,role}=await contextFor(userId);const sale=await database().sale.findFirst({where:{id:saleId,storeId:store.id,status:{in:["CONFIRMED","CORRECTED"]}},include:{createdBy:{select:{name:true,email:true}},lines:true,correction:{include:{actor:{select:{name:true,email:true}}}}}});if(!sale)throw new SalesError("NOT_FOUND","Sale not found.",404);const movements=await database().inventoryMovement.findMany({where:{storeId:store.id,sourceId:sale.id,sourceType:{in:["SALE","SALE_CORRECTION"]}},orderBy:{createdAt:"asc"},select:{id:true,productId:true,type:true,quantityDelta:true,previousQuantity:true,resultingQuantity:true,createdAt:true,sourceType:true}});return{...sale,status:sale.status as "CONFIRMED"|"CORRECTED",createdAt:sale.createdAt.toISOString(),confirmedAt:sale.confirmedAt?.toISOString()??null,correction:sale.correction?{...sale.correction,createdAt:sale.correction.createdAt.toISOString()}:null,totalAmount:sale.totalAmount.toString(),lines:sale.lines.map(line=>({...line,unitPrice:line.unitPrice.toString(),lineTotal:line.lineTotal.toString()})),movements:movements.map(movement=>({...movement,createdAt:movement.createdAt.toISOString()})),canCorrect:role==="OWNER"&&sale.status==="CONFIRMED"};}

export async function correctSale(userId:string,saleId:string,raw:unknown){const {store,role}=await contextFor(userId);requireSaleOwner(role);const input=correctionInput.parse(raw);const requestHash=hash({saleId,reason:input.reason});for(let attempt=0;attempt<3;attempt++)try{return await database().$transaction(async tx=>{const prior=await tx.idempotencyKey.findUnique({where:{storeId_scope_key:{storeId:store.id,scope:"CORRECT_SALE",key:input.idempotencyKey}}});if(prior){if(prior.requestHash!==requestHash)throw new SalesError("IDEMPOTENCY_CONFLICT","This request was already used for another correction.",409);return prior.response;}
  const sale=await tx.sale.findFirst({where:{id:saleId,storeId:store.id},include:{lines:{include:{product:{include:{balance:true}}}},correction:true}});if(!sale)throw new SalesError("NOT_FOUND","Sale not found.",404);if(sale.status!=="CONFIRMED"||sale.correction)throw new SalesError("ALREADY_CORRECTED","This sale has already been corrected.",409);const correlationId=randomUUID();for(const line of sale.lines){const balance=line.product.balance!;const update=await tx.inventoryBalance.updateMany({where:{storeId:store.id,productId:line.productId,version:balance.version},data:{quantity:{increment:line.quantity},version:{increment:1}}});if(update.count!==1)throw new SalesError("STOCK_CHANGED","Stock changed while correcting this sale. Try again.",409);await tx.inventoryMovement.create({data:{storeId:store.id,productId:line.productId,actorId:userId,type:"REVERSAL",quantityDelta:line.quantity,previousQuantity:balance.quantity,resultingQuantity:balance.quantity+line.quantity,sourceType:"SALE_CORRECTION",sourceId:sale.id,correlationId}});}const correction=await tx.saleCorrection.create({data:{storeId:store.id,saleId:sale.id,actorId:userId,reason:input.reason,correlationId}});await tx.sale.update({where:{id:sale.id},data:{status:"CORRECTED"}});const response={saleId:sale.id,correctionId:correction.id};await tx.auditEvent.create({data:{storeId:store.id,actorId:userId,action:"SALE_CORRECTED",entityType:"Sale",entityId:sale.id,correlationId,before:{status:"CONFIRMED"},after:{status:"CORRECTED",reason:input.reason}}});await tx.idempotencyKey.create({data:{storeId:store.id,scope:"CORRECT_SALE",key:input.idempotencyKey,requestHash,status:"COMPLETED",response,expiresAt:new Date(Date.now()+7*86_400_000)}});return response;},{isolationLevel:"Serializable"});}catch(error){if((error as {code?:string}).code==="P2034"&&attempt<2)continue;throw error;}throw new SalesError("STOCK_CHANGED","Stock changed. Try the correction again.",409);}

export async function dashboardSales(userId:string){const {store}=await contextFor(userId);const start=rangeStart("today");const [summary,recent]=await Promise.all([database().sale.aggregate({where:{storeId:store.id,status:"CONFIRMED",confirmedAt:{gte:start}},_sum:{totalAmount:true,totalQuantity:true},_count:{id:true}}),database().sale.findMany({where:{storeId:store.id,status:{in:["CONFIRMED","CORRECTED"]}},orderBy:{confirmedAt:"desc"},take:4,select:{id:true,status:true,totalAmount:true,totalQuantity:true,confirmedAt:true}})]);return{summary:{amount:summary._sum.totalAmount?.toString()??"0",quantity:summary._sum.totalQuantity??0,count:summary._count.id},recent:recent.map(sale=>({...sale,totalAmount:sale.totalAmount.toString()}))};}
