"use client";
/* Receipt previews use short-lived blob or signed URLs and intentionally bypass image optimization. */
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { ChangeEvent, DragEvent, useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";
import { InlineLoading, LoadingButtonContent } from "@/components/loading";
import { useDialogFocus } from "@/components/use-dialog-focus";
import { loadingCopy } from "@/modules/i18n/messages";
import { receiptUploadErrorMessage, ReceiptUploadTransportError } from "@/modules/receipts/presentation/upload-errors";

const copy={EN:{back:"Back to receipts",title:"Scan a receipt",subtitle:"Take a photo or upload an image. Tindahan will prepare it, and you'll review everything before anything changes.",drag:"Drag a photo here",or:"or choose an option below",take:"Take photo",upload:"Upload file",selected:"Photo ready to upload",replace:"Choose another photo",start:"Prepare receipt",uploading:"Uploading receipt",processing:"Processing receipt",processingHelp:"You can leave this page. The receipt will stay here and be ready when processing finishes.",ready:"Ready to review",review:"Review receipt",failed:"We couldn't process this receipt.",retry:"Try again",uploadAnother:"Upload a different photo",remove:"Remove failed upload",removing:"Removing upload",discardError:"We couldn't remove the failed upload. Try again.",retake:"Retake photo",tip:"For a clear photo:",tipBody:"lay the receipt flat, use good lighting, and include the whole receipt in the frame.",camera:"Take a receipt photo",capture:"Use this photo",cancel:"Cancel",cameraError:"The camera couldn't start. Upload a photo instead.",fileError:"Choose a JPEG, PNG, or WebP image smaller than 10 MB."},FIL:{back:"Bumalik sa resibo",title:"I-scan ang resibo",subtitle:"Kumuha ng litrato o mag-upload ng imahe. Ihahanda ito ng Tindahan, at susuriin mo muna ang lahat bago magbago ang kahit ano.",drag:"I-drag ang litrato dito",or:"o pumili sa ibaba",take:"Kumuha ng litrato",upload:"Mag-upload",selected:"Handa nang i-upload ang litrato",replace:"Pumili ng ibang litrato",start:"Ihanda ang resibo",uploading:"Ina-upload ang resibo",processing:"Inihahanda ang resibo",processingHelp:"Puwede kang umalis sa pahinang ito. Mananatili rito ang resibo at magiging handa kapag tapos na.",ready:"Handa nang suriin",review:"Suriin ang resibo",failed:"Hindi naihanda ang resibo.",retry:"Subukan ulit",uploadAnother:"Mag-upload ng ibang litrato",remove:"Alisin ang nabigong upload",removing:"Inaalis ang upload",discardError:"Hindi naalis ang nabigong upload. Subukan ulit.",retake:"Kumuha ulit",tip:"Para sa malinaw na litrato:",tipBody:"ilatag nang patag ang resibo, gumamit ng magandang liwanag, at isama ang buong resibo sa frame.",camera:"Kumuha ng litrato ng resibo",capture:"Gamitin ang litratong ito",cancel:"Kanselahin",cameraError:"Hindi nagsimula ang camera. Mag-upload na lang ng litrato.",fileError:"Pumili ng JPEG, PNG, o WebP na mas maliit sa 10 MB."}} as const;
type Stage="idle"|"selected"|"uploading"|"processing"|"ready"|"failed";

export function ReceiptUploadClient({locale}:{locale:"EN"|"FIL"}){
  const t=copy[locale],router=useRouter();const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState("");const [stage,setStage]=useState<Stage>("idle");const [progress,setProgress]=useState(0);const [message,setMessage]=useState("");const [receiptId,setReceiptId]=useState("");const [camera,setCamera]=useState(false);const [discarding,setDiscarding]=useState(false);const input=useRef<HTMLInputElement>(null);const stream=useRef<MediaStream|null>(null);const video=useRef<HTMLVideoElement>(null);const dialog=useRef<HTMLDivElement>(null);
  const stopCamera=useCallback(()=>{stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(video.current)video.current.srcObject=null;},[]);
  const accept=useCallback((next:File)=>{if(!["image/jpeg","image/png","image/webp"].includes(next.type)||next.size<=0||next.size>10*1024*1024){setMessage(t.fileError);return;}if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(URL.createObjectURL(next));setStage("selected");setMessage("");},[preview,t.fileError]);
  useEffect(()=>()=>{stopCamera();if(preview)URL.revokeObjectURL(preview);},[preview,stopCamera]);
  async function openCamera(){setCamera(true);setMessage("");try{const next=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});stream.current=next;requestAnimationFrame(()=>{if(video.current)video.current.srcObject=next;});}catch{setMessage(t.cameraError);setCamera(false);stopCamera();input.current?.click();}}
  const closeCamera=useCallback(()=>{stopCamera();setCamera(false);},[stopCamera]);
  useDialogFocus(camera,dialog,closeCamera);
  function capture(){const source=video.current;if(!source?.videoWidth)return;const canvas=document.createElement("canvas");canvas.width=source.videoWidth;canvas.height=source.videoHeight;canvas.getContext("2d")?.drawImage(source,0,0);canvas.toBlob(blob=>{if(blob)accept(new File([blob],`receipt-${Date.now()}.jpg`,{type:"image/jpeg"}));closeCamera();},"image/jpeg",0.9);}
  function uploadToTarget(url:string,headers:Record<string,string>,selected:File){return new Promise<void>((resolve,reject)=>{const request=new XMLHttpRequest();const fail=(code:"UPLOAD_REJECTED"|"UPLOAD_NETWORK_ERROR"|"UPLOAD_TIMEOUT")=>{console.warn({level:"warn",message:"receipt_upload_transport_failed",code,status:request.status,pageOrigin:window.location.origin,targetOrigin:new URL(url).origin,online:navigator.onLine});reject(new ReceiptUploadTransportError(code));};request.open("PUT",url);request.timeout=120_000;Object.entries(headers).forEach(([key,value])=>request.setRequestHeader(key,value));request.upload.onprogress=event=>{if(event.lengthComputable)setProgress(Math.round(event.loaded/event.total*100));};request.onload=()=>request.status>=200&&request.status<300?resolve():fail("UPLOAD_REJECTED");request.onerror=()=>fail("UPLOAD_NETWORK_ERROR");request.ontimeout=()=>fail("UPLOAD_TIMEOUT");request.send(selected);});}
  async function prepare(){if(!file)return;setStage("uploading");setMessage("");setProgress(0);try{const response=await fetch("/api/receipts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({filename:file.name,mimeType:file.type,sizeBytes:file.size,idempotencyKey:crypto.randomUUID()})});const body=await response.json() as {receiptId?:string;upload?:{url:string;headers:Record<string,string>};error?:string};if(!response.ok||!body.receiptId||!body.upload)throw new Error(body.error);setReceiptId(body.receiptId);await uploadToTarget(body.upload.url,body.upload.headers,file);const completed=await fetch(`/api/receipts/${body.receiptId}/complete`,{method:"POST"});const completeBody=await completed.json() as {error?:string};if(!completed.ok)throw new Error(completeBody.error);setStage("processing");}catch(error){setMessage(receiptUploadErrorMessage(locale,error));setStage("failed");}}
  useEffect(()=>{if(stage!=="processing"||!receiptId)return;let delay=1800,stopped=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const response=await fetch(`/api/receipts/${receiptId}/status`);const body=await response.json() as {status:string;message?:string};if(!response.ok)throw new Error();if(body.status==="REVIEW_READY"){setStage("ready");router.refresh();return;}if(body.status==="FAILED"){setMessage(locale==="FIL"?t.failed:body.message??t.failed);setStage("failed");return;}}catch{}delay=Math.min(Math.round(delay*1.45),8000);if(!stopped)timer=setTimeout(poll,delay);};timer=setTimeout(poll,delay);return()=>{stopped=true;clearTimeout(timer);};},[locale,receiptId,router,stage,t.failed]);
  async function retry(){if(!receiptId){setStage(file?"selected":"idle");return;}setStage("processing");setMessage("");const response=await fetch(`/api/receipts/${receiptId}/retry`,{method:"POST"});if(!response.ok){const body=await response.json() as {error?:string};setMessage(locale==="FIL"?t.failed:body.error??t.failed);setStage("failed");}}
  async function discardFailed(){if(!receiptId)return true;setDiscarding(true);try{const response=await fetch(`/api/receipts/${receiptId}`,{method:"DELETE"});if(!response.ok){const body=await response.json() as {error?:string};throw new Error(body.error);}setReceiptId("");router.refresh();return true;}catch(problem){setMessage(problem instanceof Error&&problem.message?problem.message:t.discardError);return false;}finally{setDiscarding(false);}}
  async function choose(next:File){if(stage==="failed"&&!(await discardFailed()))return;accept(next);if(input.current)input.current.value="";}
  async function removeFailed(){if(!(await discardFailed()))return;if(preview)URL.revokeObjectURL(preview);setFile(null);setPreview("");setProgress(0);setMessage("");setStage("idle");router.push("/receipts");}
  function dropped(event:DragEvent){event.preventDefault();const next=event.dataTransfer.files[0];if(next)accept(next);}
  return <>
    <Link className="back-link" href="/receipts"><Icon name="arrowLeft" className="icon icon-sm"/>{t.back}</Link><div className="content-header receipt-upload-header"><h1>{t.title}</h1><p className="text-muted">{t.subtitle}</p></div>
    <div className="receipt-upload-column">
      {(stage==="idle"||stage==="selected")&&<div className="dropzone" onDragOver={event=>event.preventDefault()} onDrop={dropped} aria-label={t.drag}>{preview?<img className="receipt-upload-preview" src={preview} alt={locale==="FIL"?"Napiling litrato ng resibo":"Selected receipt photo"}/>:<span className="dropzone-icon"><Icon name="upload" className="icon icon-lg"/></span>}<div><p className="font-medium">{preview?t.selected:t.drag}</p><p className="text-muted text-sm">{preview?file?.name:t.or}</p></div><div className="receipt-upload-actions"><button className="btn btn-primary" type="button" onClick={openCamera}><Icon name="camera"/>{preview?t.retake:t.take}</button><button className="btn btn-secondary" type="button" onClick={()=>input.current?.click()}><Icon name="upload"/>{preview?t.replace:t.upload}</button></div><input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event:ChangeEvent<HTMLInputElement>)=>{const next=event.target.files?.[0];if(next)void choose(next);}}/>{preview&&<button className="btn btn-accent btn-block" type="button" onClick={prepare}>{t.start}</button>}</div>}
      {stage==="uploading"&&<div className="dropzone receipt-processing-zone" aria-busy="true"><span className="dropzone-icon"><Icon name="loader" className="icon icon-lg loading-icon-spin"/></span><InlineLoading message={loadingCopy(locale,"uploadingReceipt")} announce={false}/><div className="progress-track receipt-upload-progress"><div className="progress-fill" style={{width:`${progress}%`}}/></div><p className="text-sm text-muted">{progress}%</p></div>}
      {stage==="processing"&&<div className="dropzone receipt-processing-zone" aria-busy="true"><span className="dropzone-icon"><Icon name="loader" className="icon icon-lg loading-icon-spin"/></span><p className="font-medium">{t.processing}</p><p className="text-muted text-sm">{t.processingHelp}</p><Link className="btn btn-secondary" href="/receipts">{t.back}</Link></div>}
      {stage==="ready"&&<div className="dropzone receipt-ready-zone"><span className="dropzone-icon"><Icon name="check" className="icon icon-lg"/></span><p className="font-medium">{t.ready}</p><Link className="btn btn-primary" href={`/receipts/${receiptId}/review`}>{t.review}</Link></div>}
      {stage==="failed"&&<div className="dropzone receipt-failed-zone"><span className="dropzone-icon"><Icon name="alert" className="icon icon-lg"/></span><p className="font-medium">{t.failed}</p><p className="text-muted text-sm">{message}</p><div className="receipt-upload-actions"><button className="btn btn-primary" type="button" disabled={discarding} onClick={()=>input.current?.click()}><Icon name="upload"/>{t.uploadAnother}</button><button className="btn btn-secondary" type="button" disabled={discarding} onClick={retry}><Icon name="refresh"/>{t.retry}</button></div><input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event:ChangeEvent<HTMLInputElement>)=>{const next=event.target.files?.[0];if(next)void choose(next);}}/>{receiptId&&<button className="btn btn-danger" type="button" disabled={discarding} onClick={removeFailed}>{discarding?<LoadingButtonContent message={t.removing}/>:<><Icon name="xCircle"/>{t.remove}</>}</button>}</div>}
      {message&&stage!=="failed"&&<p className="field-error" role="alert">{message}</p>}
      <div className="banner banner-info receipt-photo-tip"><Icon name="info"/><span><strong>{t.tip}</strong> {t.tipBody}</span></div>
    </div>
    {camera&&<div className="overlay-scrim camera-dialog-layer is-open" onMouseDown={event=>{if(event.target===event.currentTarget)closeCamera();}}><div ref={dialog} className="modal modal-wide is-open receipt-camera-dialog" role="dialog" aria-modal="true" aria-labelledby="receipt-camera-title"><div className="modal-header"><h3 id="receipt-camera-title">{t.camera}</h3><button className="btn-icon btn-ghost" aria-label={t.cancel} onClick={closeCamera}><Icon name="x"/></button></div><div className="scanner-surface is-scanning"><video ref={video} className="scanner-video" autoPlay muted playsInline/><span className="receipt-camera-frame"/></div><div className="modal-actions"><button className="btn btn-secondary" onClick={closeCamera}>{t.cancel}</button><button className="btn btn-primary" onClick={capture}><Icon name="camera"/>{t.capture}</button></div></div></div>}
  </>;
}
