"use client";
import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

type Item = { id:string; name:string; sellingUnit:string; sellingPrice:string; quantity:number; lowStockThreshold:number; stockStatus:"in_stock"|"low_stock"|"out_of_stock"; category:{name:string}|null; supplier:string|null; hasBarcode:boolean };
type Results = { items:Item[]; counts:{all:number;low:number;out:number;recent:number;categories:number}; nextCursor:string|null };
const units = ["PIECE","PACK","SACHET","BOTTLE","CAN","BOX","DOZEN","GRAM","KILOGRAM","MILLILITER","LITER","SACK","CASE","TRAY","OTHER"];
const copy = {
 EN:{ productsAcross:"products across",categories:"categories",add:"Add product",all:"All",low:"Low Stock",out:"Out of Stock",recent:"Recently Updated",search:"Search products by name, barcode, category, or supplier",list:"List view",grid:"Grid view",inStock:"In stock",lowStock:"Low stock",outStock:"Out of stock",noMatch:"No products match",noMatchBody:"Try a different search or clear the current filter.",clear:"Clear search and filters",empty:"No products yet",emptyBody:"Add your first product to start tracking stock.",loading:"Loading products…",error:"We couldn't load inventory. Try again.",retry:"Try again",name:"Product name",category:"Category",supplier:"Supplier",soldBy:"Sold by",otherUnit:"How do you sell it?",barcodeOption:"Add a barcode option",identify:"How should this product be identified?",scanEnter:"Scan or enter",packageBarcode:"Use the barcode on the package",generate:"Generate barcode",tingi:"Best for tingi items",none:"No barcode",without:"Continue without one",manufacturer:"Manufacturer barcode",price:"Price",cost:"Purchase cost (optional)",starting:"Starting quantity",threshold:"Low-stock threshold",cancel:"Cancel",save:"Add product",added:"Product added.",validBarcode:"Enter a valid 8–14 digit barcode."},
 FIL:{ productsAcross:"produkto sa",categories:"kategorya",add:"Magdagdag ng produkto",all:"Lahat",low:"Paubos na",out:"Ubos na",recent:"Kamakailang Binago",search:"Maghanap ayon sa pangalan, barcode, kategorya, o supplier",list:"Listahan",grid:"Grid",inStock:"May stock",lowStock:"Paubos na",outStock:"Ubos na",noMatch:"Walang tugmang produkto",noMatchBody:"Subukan ang ibang search o alisin ang kasalukuyang filter.",clear:"Alisin ang search at filter",empty:"Wala pang produkto",emptyBody:"Idagdag ang unang produkto para masimulang subaybayan ang stock.",loading:"Kinukuha ang mga produkto…",error:"Hindi makuha ang imbentaryo. Subukan ulit.",retry:"Subukan ulit",name:"Pangalan ng produkto",category:"Kategorya",supplier:"Supplier",soldBy:"Ibinebenta bilang",otherUnit:"Paano ito ibinebenta?",barcodeOption:"Magdagdag ng opsyon sa barcode",identify:"Paano kikilalanin ang produktong ito?",scanEnter:"I-scan o ilagay",packageBarcode:"Gamitin ang barcode sa pakete",generate:"Gumawa ng barcode",tingi:"Para sa tingi na produkto",none:"Walang barcode",without:"Magpatuloy nang wala nito",manufacturer:"Barcode ng gumawa",price:"Presyo",cost:"Halaga ng bili (opsyonal)",starting:"Panimulang dami",threshold:"Bilang bago matawag na paubos",cancel:"Kanselahin",save:"Idagdag",added:"Naidagdag ang produkto.",validBarcode:"Maglagay ng wastong barcode na 8–14 numero."}
} as const;

export function InventoryClient({ initial, initialView, locale }:{initial:Results;initialView:"LIST"|"GRID";locale:"EN"|"FIL"}) {
 const t=copy[locale]; const router=useRouter(); const [results,setResults]=useState(initial); const [view,setView]=useState(initialView); const [filter,setFilter]=useState("all"); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [modal,setModal]=useState(false); const [barcodeOpen,setBarcodeOpen]=useState(false); const [barcodeChoice,setBarcodeChoice]=useState("NONE"); const [other,setOther]=useState(false); const [notice,setNotice]=useState(""); const dialog=useRef<HTMLDivElement>(null);
 async function load(q=query,f=filter){setLoading(true);setError("");try{const response=await fetch(`/api/inventory/products?q=${encodeURIComponent(q)}&filter=${f}`);if(!response.ok)throw new Error();setResults(await response.json())}catch{setError(t.error)}finally{setLoading(false)}}
 useEffect(()=>{const timer=setTimeout(()=>void load(query,filter),300);return()=>clearTimeout(timer)},[query,filter]);
 useEffect(()=>{if(!modal)return; const previous=document.activeElement as HTMLElement|null; dialog.current?.querySelector<HTMLElement>("input")?.focus(); const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setModal(false);if(event.key==="Tab"&&dialog.current){const focus=[...dialog.current.querySelectorAll<HTMLElement>('button,input,select')].filter(x=>!x.hasAttribute('disabled'));const first=focus[0],last=focus.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previous?.focus()}},[modal]);
 async function changeView(next:"LIST"|"GRID"){setView(next);await fetch("/api/inventory/view",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({view:next})})}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form);const response=await fetch("/api/inventory/products",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,barcodeChoice,sellingPrice:Number(payload.sellingPrice),latestPurchaseCost:payload.latestPurchaseCost?Number(payload.latestPurchaseCost):null,startingQuantity:Number(payload.startingQuantity),lowStockThreshold:Number(payload.lowStockThreshold)})});const body=await response.json();if(!response.ok){setError(body.error);return}setModal(false);setNotice(t.added);await load();router.refresh()}
 const status=(item:Item)=>item.stockStatus==="out_of_stock"?["badge-danger",t.outStock,"x"]:item.stockStatus==="low_stock"?["badge-warning",t.lowStock,"alert"]:["badge-success",t.inStock,"check"];
 return <><div className="content-header"><div className="content-header-row"><div><h1>{locale==="FIL"?"Imbentaryo":"Inventory"}</h1><p className="text-muted">{results.counts.all} {t.productsAcross} {results.counts.categories} {t.categories}</p></div><button className="btn btn-primary" onClick={()=>setModal(true)}><Icon name="plus"/>{t.add}</button></div></div>
 <div className="section-header" style={{marginBottom:"var(--space-4)"}}><div className="chip-row" role="group" aria-label={locale==="FIL"?"Salain ang imbentaryo":"Filter inventory"}>{[["all",t.all,results.counts.all],["low",t.low,results.counts.low],["out",t.out,results.counts.out],["recent",t.recent,results.counts.recent]].map(([key,label,count])=><button key={String(key)} type="button" className={`chip${filter===key?" active":""}`} onClick={()=>setFilter(String(key))}>{label} <span className="count">{count}</span></button>)}</div></div>
 <div className="input-group" style={{maxWidth:420,marginBottom:"var(--space-5)"}}><Icon name="search"/><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} aria-label={t.search}/></div>
 <div className="inventory-results-bar"><p className="text-sm text-muted" role="status" aria-live="polite">{loading?t.loading:`${results.items.length} ${locale==="FIL"?"produkto":"products"}`}</p><div className="segmented view-toggle" role="group" aria-label={locale==="FIL"?"Ayos ng imbentaryo":"Inventory view"}><button className={view==="LIST"?"active":""} aria-pressed={view==="LIST"} onClick={()=>changeView("LIST")}><Icon name="list" className="icon icon-sm"/>{t.list}</button><button className={view==="GRID"?"active":""} aria-pressed={view==="GRID"} onClick={()=>changeView("GRID")}><Icon name="grid" className="icon icon-sm"/>{t.grid}</button></div></div>
 {error?<div className="empty-state"><div className="empty-icon"><Icon name="alert"/></div><h3>{error}</h3><button className="btn btn-secondary" onClick={()=>load()}>{t.retry}</button></div>:results.items.length===0?<div className="empty-state"><div className="empty-icon"><Icon name="package"/></div><h3>{query||filter!=="all"?t.noMatch:t.empty}</h3><p className="empty-body">{query||filter!=="all"?t.noMatchBody:t.emptyBody}</p>{query||filter!=="all"?<button className="btn btn-secondary" onClick={()=>{setQuery("");setFilter("all")}}>{t.clear}</button>:<button className="btn btn-secondary" onClick={()=>setModal(true)}>{t.add}</button>}</div>:view==="LIST"?<div className="row-list">{results.items.map(item=>{const s=status(item);return <Link className="row-item is-interactive" href={`/inventory/${item.id}`} key={item.id}><span className="product-thumb"><Icon name="bag"/></span><span className="row-main"><span className="row-title">{item.name}</span><span className="row-meta">{item.category?.name??(locale==="FIL"?"Walang kategorya":"Uncategorized")}{item.supplier?` · ${item.supplier}`:""}</span></span><span className={`badge ${s[0]}`}><Icon name={s[2] as "check"|"alert"|"x"} className="icon icon-sm"/>{s[1]}</span><span className="row-value">{item.quantity} <span className="text-muted text-sm font-medium">{item.sellingUnit.toLowerCase()}</span></span></Link>})}</div>:<div className="inventory-grid">{results.items.map(item=>{const s=status(item);return <Link className="inventory-card" href={`/inventory/${item.id}`} key={item.id}><span className="product-thumb"><Icon name="bag"/></span><div className="inventory-card-body"><span className="row-title">{item.name}</span><span className="row-meta">{item.category?.name??(locale==="FIL"?"Walang kategorya":"Uncategorized")}</span><span className={`badge ${s[0]}`}><Icon name={s[2] as "check"|"alert"|"x"} className="icon icon-sm"/>{s[1]}</span><strong>{item.quantity} <span className="text-muted text-sm font-medium">{item.sellingUnit.toLowerCase()}</span></strong><span className="text-sm">₱{Number(item.sellingPrice).toFixed(2)}{item.hasBarcode?" · Barcode":""}</span></div></Link>})}</div>}
 {notice&&<div className="toast is-visible" role="status">{notice}</div>}
 {modal&&<div className="modal is-open" role="dialog" aria-modal="true" aria-labelledby="add-title"><div className="modal-card" ref={dialog}><div className="modal-header"><h3 id="add-title">{t.add}</h3><button className="btn-icon btn-ghost" aria-label={t.cancel} onClick={()=>setModal(false)}><Icon name="x"/></button></div><form onSubmit={submit} style={{display:"flex",flexDirection:"column",gap:"var(--space-4)"}}><div className="field"><label className="field-label" htmlFor="p-name">{t.name}</label><input className="input" id="p-name" name="name" required maxLength={160}/></div><div className="form-row"><div className="field"><label className="field-label" htmlFor="p-cat">{t.category}</label><input className="input" id="p-cat" name="category"/></div><div className="field"><label className="field-label" htmlFor="p-unit">{t.soldBy}</label><select className="select" id="p-unit" name="sellingUnit" required onChange={e=>setOther(e.target.value==="OTHER")}>{units.map(unit=><option key={unit}>{unit}</option>)}</select></div></div>{other&&<div className="field"><label className="field-label" htmlFor="p-other">{t.otherUnit}</label><input className="input" id="p-other" name="otherUnitRaw" required/></div>}<div className="field"><label className="field-label" htmlFor="p-supplier">{t.supplier}</label><input className="input" id="p-supplier" name="supplier"/></div>
 <button type="button" className="btn btn-soft" aria-expanded={barcodeOpen} onClick={()=>setBarcodeOpen(!barcodeOpen)}><Icon name="tag"/>{t.barcodeOption}</button>{barcodeOpen&&<section className="barcode-panel"><p className="field-label">{t.identify}</p><div className="barcode-choice-grid">{[["MANUFACTURER",t.scanEnter,t.packageBarcode],["INTERNAL",t.generate,t.tingi],["NONE",t.none,t.without]].map(([value,title,body])=><label className="barcode-choice" key={value}><input type="radio" name="choice" checked={barcodeChoice===value} onChange={()=>setBarcodeChoice(value)}/><span><strong>{title}</strong><br/><span className="text-sm text-muted">{body}</span></span></label>)}</div>{barcodeChoice==="MANUFACTURER"&&<div className="field"><label className="field-label" htmlFor="p-barcode">{t.manufacturer}</label><input className="input" id="p-barcode" name="manufacturerBarcode" inputMode="numeric" pattern="[0-9 -]{8,20}" required/></div>}</section>}
 <div className="form-row"><div className="field"><label className="field-label" htmlFor="p-price">{t.price}</label><input className="input" id="p-price" name="sellingPrice" type="number" min="0" step="0.01" required/></div><div className="field"><label className="field-label" htmlFor="p-qty">{t.starting}</label><input className="input" id="p-qty" name="startingQuantity" type="number" min="0" step="1" defaultValue="0" required/></div></div><div className="form-row"><div className="field"><label className="field-label" htmlFor="p-cost">{t.cost}</label><input className="input" id="p-cost" name="latestPurchaseCost" type="number" min="0" step="0.01"/></div><div className="field"><label className="field-label" htmlFor="p-threshold">{t.threshold}</label><input className="input" id="p-threshold" name="lowStockThreshold" type="number" min="0" step="1" defaultValue="0" required/></div></div>{error&&<p className="field-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setModal(false)}>{t.cancel}</button><button className="btn btn-primary" type="submit">{t.save}</button></div></form></div></div>}</>;
}
